spring:
  application:
    name: ${SPRING_APP_NAME:easybank}

  # Profiles
  config:
    import: application_prod.properties
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:172.17.0.3}:${DATABASE_PORT:5432}/eazybank
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
    hibernate:
      ddl-auto: create

server:
  port: 8080
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:2m}


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}





